
modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
[[mods]]
modId = "wasteland"
version = "${file.jarVersion}"
displayName = "Wasteland Things"
authors="PiotrO15"
description = "Blocks and items used in Verdant Idea modpack"
[[dependencies.wasteland]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.wasteland]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.2)"
ordering = "NONE"
side = "BOTH"